blank_issues_enabled: false
contact_links:
  - name: Read the docs before opening an issue
    url: https://github.com/seanpm2001/seanpm2001/tree/master/Docs/
    about: Please read the docs before opening an issue.
  - name: I want to help develop
    url: https://github.com/seanpm2001/Teams/discussions/
    about: Thank you for your interest in this project! Please consider joining a team to start developing with me
  - name: I want to help translate
    url: https://github.com/seanpm2001/Teams/discussions/
    about: Thank you for your interest in this project! Please consider joining a team to start translating projects with me

# File info
# File version: 1 (2022, Thursday, May 26th at 5:55 pm PST)
# File type: GitHub issue template config file (*.yml)
# Line count (including blank lines and compiler line): 17
